version: '3'

services:
  # Readymade-Images
  
  # nginx Web Server
  web-server:
    image: nginx:1.25.2-alpine
    container_name: nginx-web-server
    ports:
      - 1111:80
    volumes:
      - ./nginx-web-server:/usr/share/nginx/html
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
  
  # Alpine Linux OS
  linux-os:
    image: alpine:latest
    container_name: alpine_with_sqlite
    # 1- Install sqlite ; 2 - Start Sqlite ; 3 - Keep it running
    command: sh -c "apk add --no-cache sqlite && sqlite3 /data/mydatabase.db && tail -f /dev/null"
    volumes:
      - ./sqlite-data:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3    

  # PHP Web App
  web-app:
    image: php:apache-bullseye
    container_name: php-web-app
    volumes:
      - ./php-web-app:/var/www/html/
    ports:
      - 2222:80
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  # Java Code
  java-code:
    image: java:8u111-jdk-alpine
    container_name: java_code
    volumes:
      - ./java-time-zones:/app
    working_dir: /app
    command: sh -c "javac DateTimeEg.java && java DateTimeEg"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3


  # Custom-Image
  json-reader:
    build: ./python-json-reader
    container_name: python_code
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3